config/routes.rb
Rails.application.routes.draw do
  get 'visitor/index'

  get 'visitor/show'

  get 'visitor/about'

  get 'visitor/allPost'

  devise_for :users
  resources :posts do
    resources :comments
  end

root 'visitor#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_attached_file :image, styles: { medium: "500x600>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


    def after_sign_in_path_for(resource)
        posts_path
    end

    def after_sign_out_for(resource)
        root_path
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(comment_params)

      if @comment.save
          redirect_to post_path(@post)
      else
        render 'new'
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:name, :email, :body)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!
  #before_action :right_owner


  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.posts.all.order("created_at Desc")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # if current_user != Post.find(params[:id]).user
    #     redirect_to new_user_session_path
    # end
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
    if current_user != Post.find(params[:id]).user
        redirect_to new_user_session_path
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      #@post = current_user.posts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :body, :image)
    end





end

app/controllers/visitor_controller.rb
class VisitorController < ApplicationController
  def index
    @posts = Post.all.order("created_at Desc LIMIT 3")
  end

  def show
  end

  def about
  end

  def allPost
    @posts = Post.all.order("created_at Desc")

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/views/comments/_comment.html.erb
<div class="blockquote">
  <p><%= comment.name%> || <%= comment.email %></p>

  <p><%= comment.body  %></p>

</div>

app/views/comments/_form.html.erb
<%=form_for([@post, @post.comments.build]) do |f| %>

<form>
  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'%>
  </div>
  <div class="field form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control'%>
  </div>
  <div class="field form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control'%>
  </div>

  <div class="actions btn btn-default">
    <%= f.submit %>
  </div>
</form>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloggerApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- class="navbar-brand"<%=link_to "Blogger for you", root_path, class: "navbar-brand" %> -->

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if current_user%>
            <li><%=link_to "New Post", new_post_path %></li>
            <li class="active"> <%=link_to "Home", root_path %> </li>

            <% else %>
            <li class="active"> <%=link_to "Home", root_path %> </li>
            <li class="active"> <%=link_to "All Post", visitor_allPost_path %> </li>
            <li class="active"> <%=link_to "About", visitor_about_path %> </li>

            <% end%>

          </ul>
          <ul class="nav navbar-nav navbar-right">

            <% if current_user%>
            <li><%=link_to "Logout", destroy_user_session_path , method: :delete %></li>
            <%else %>
            <li><%=link_to "Log-in", new_user_session_path %></li>
            <li><%=link_to "Sign-up", new_user_registration_path %></li>


            <%end%>

            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li></li>
              </ul>
            </li> -->
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>



    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>

<footer>
  <blockquote>
    <p>a seedy jobe side projec</p>
    <p>&copy; for no reason</p>
  </blockquote>

</footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <div class="field form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>
  </div>

  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="actions btn btn-default">
    <%= f.submit %>
  </div>
</form>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>


    <% @posts.each do |post| %>
        <h2><%= post.title %></h2>
        <%= link_to "View Post", post_path(post), class: "btn btn-default" %>

        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>


<br>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>Posted By <%= @post.user.email %> || <%= time_ago_in_words(@post.created_at) %> </p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
    <%= image_tag(@post.image.url(:medium)) %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<h3>COMMENTS:- </h3>

<%= render @post.comments %>


<h3>make a comment</h3>

<%= render 'comments/form' %>


<% if current_user == Post.find(params[:id]).user%>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<% end%>

app/views/visitor/about.html.erb
<h1>about the blog</h1>

app/views/visitor/allPost.html.erb
<p id="notice"><%= notice %></p>
<h2>all post</h2>

<h1>Posts</h1>
<!-- use slice something -->

<% @posts.each_slice(3) do |slice| %>
	<div class="row">
		   <% slice.each do |post| %>
		    	<div class="col-md-3 col-sm-3 col-lg postBlock">
		        <h2><%= post.title %></h2>
		     <%= link_to "View Post", post_path(post), class: "btn btn-default" %>
			</div>
		    <% end %>
	</div>
<% end %>
<br>

app/views/visitor/index.html.erb
<p id="notice"><%= notice %></p>

<jumbotrom>Posts</jumbotrom>
<header>
  <div class="container-fluid hh">
      <h1>dgwhetjythg</h1>
      <p>somehing inspiring</p>
      <p>somehing inspiring</p>
      <p>somehing inspiring</p>
      <p>somehing inspiring</p>
      <p>somehing inspiring</p>
      <p>somehing inspiring</p>
  </div>
</header>


      <div class="row" >

        <% @posts.each do |post| %>

          <div class="col-md-3 col-sm-3 col-lg postBlock">
              <h2><%= post.title %></h2>
              <%= link_to "View Post", post_path(post), class: "btn btn-default" %>

          </div>

            <% end %>
      </div>


<br>

app/views/visitor/show.html.erb
<p id="notice"><%= notice %></p>

<div class="postTitle">
  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>
</div>


<p>Posted By <%= @post.user.email %> || <%= time_ago_in_words(@post.created_at) %> </p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
    <%= image_tag(@post.image.url(:medium)) %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<h3>COMMENTS:- </h3>

<%= render @post.comments %>


<h3>make a comment</h3>

<%= render 'comments/form' %>


<% if current_user%>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<% end%>